//FETCH ALL TOUR GROUP
export const FETCH_TOUR_GROUP_REQUEST = "FETCH_TOUR_GROUP_REQUEST"
export const FETCH_TOUR_GROUP_SUCCESS = "FETCH_TOUR_GROUP_SUCCESS"
export const FETCH_TOUR_GROUP_FAILURE = "FETCH_TOUR_GROUP_FAILURE"

//ADDDING A TOUR GROUP
export const ADD_TOUR_GROUP_REQUEST = "ADD_TOUR_GROUP_REQUEST"
export const ADD_TOUR_GROUP_SUCCESS = "ADD_TOUR_GROUP_SUCCESS"
export const ADD_TOUR_GROUP_FAILURE = "ADD_TOUR_GROUP_FAILURE"

//DELETING A TOUR GROUP
export const DELETE_TOUR_GROUP_REQUEST = "DELETE_TOUR_GROUP_REQUEST"
export const DELETE_TOUR_GROUP_SUCCESS = "DELETE_TOUR_GROUP_SUCCESS"
export const DELETE_TOUR_GROUP_FAILURE = "DELETE_TOUR_GROUP_FAILURE"
//FETCH TOUR GROUP WITH ID
export const FETCH_TOUR_GROUP_WITH_ID_REQUEST =
  "FETCH_TOUR_GROUP_WITH_ID_REQUEST"
export const FETCH_TOUR_GROUP_WITH_ID_SUCCESS =
  "FETCH_TOUR_GROUP_WITH_ID_SUCCESS"
export const FETCH_TOUR_GROUP_WITH_ID_FAILURE =
  "FETCH_TOUR_GROUP_WITH_ID_FAILURE"

//Emptying the tour group with id
export const REMOVE_TOUR_GROUP_WITH_ID = "REMOVE_TOUR_GROUP_WITH_ID"

//Updating the tour group
export const UPDATE_TOUR_GROUP_REQUEST = "UPDATE_TOUR_GROUP_REQUEST"
export const UPDATE_TOUR_GROUP_SUCCESS = "UPDATE_TOUR_GROUP_SUCCESS"
export const UPDATE_TOUR_GROUP_FAILURE = "UPDATE_TOUR_GROUP_FAILURE"

//Tour group booking request
export const GET_TOUR_GROUP_BOOKING_REQUEST = "GET_TOUR_BOOKING_REQUEST"
export const GET_TOUR_GROUP_BOOKING_SUCCESS = "GET_TOUR_BOOKING_SUCCESS"
export const GET_TOUR_GROUP_BOOKING_FAILURE = "GET_TOUR_BOOKING_FAILURE"

