//FETCH ALL TOUR GROUP
export const FETCH_TOUR_GROUP_REQUEST = "FETCH_TOUR_GROUP_REQUEST"
export const FETCH_TOUR_GROUP_SUCCESS = "FETCH_TOUR_GROUP_SUCCESS"
export const FETCH_TOUR_GROUP_FAILURE = "FETCH_TOUR_GROUP_FAILURE"

//ADDDING A TOUR GROUP
export const ADD_TOUR_GROUP_REQUEST = "ADD_TOUR_GROUP_REQUEST"
export const ADD_TOUR_GROUP_SUCCESS = "ADD_TOUR_GROUP_SUCCESS"
export const ADD_TOUR_GROUP_FAILURE = "ADD_TOUR_GROUP_FAILURE"

//DELETING A TOUR GROUP
export const DELETE_TOUR_GROUP_REQUEST = "DELETE_TOUR_GROUP_REQUEST"
export const DELETE_TOUR_GROUP_SUCCESS = "DELETE_TOUR_GROUP_SUCCESS"
export const DELETE_TOUR_GROUP_FAILURE = "DELETE_TOUR_GROUP_FAILURE"
//FETCH TOUR GROUP WITH ID
export const FETCH_TOUR_GROUP_WITH_ID_REQUEST =
  "FETCH_TOUR_GROUP_WITH_ID_REQUEST"
export const FETCH_TOUR_GROUP_WITH_ID_SUCCESS =
  "FETCH_TOUR_GROUP_WITH_ID_SUCCESS"
export const FETCH_TOUR_GROUP_WITH_ID_FAILURE =
  "FETCH_TOUR_GROUP_WITH_ID_FAILURE"

//Emptying the tour group with id
export const REMOVE_TOUR_GROUP_WITH_ID = "REMOVE_TOUR_GROUP_WITH_ID"

//Clear tour group list
export const CLEAR_TOUR_GROUP_LIST = "CLEAR_TOUR_GROUP_LIST"

//Updating the tour group
export const UPDATE_TOUR_GROUP_REQUEST = "UPDATE_TOUR_GROUP_REQUEST"
export const UPDATE_TOUR_GROUP_SUCCESS = "UPDATE_TOUR_GROUP_SUCCESS"
export const UPDATE_TOUR_GROUP_FAILURE = "UPDATE_TOUR_GROUP_FAILURE"

//Tour group booking request
export const GET_TOUR_GROUP_BOOKING_REQUEST = "GET_TOUR_BOOKING_REQUEST"
export const GET_TOUR_GROUP_BOOKING_SUCCESS = "GET_TOUR_BOOKING_SUCCESS"
export const GET_TOUR_GROUP_BOOKING_FAILURE = "GET_TOUR_BOOKING_FAILURE"

//Fetch tour groups by city (for dropdowns)
export const FETCH_TOUR_GROUPS_BY_CITY_REQUEST = "FETCH_TOUR_GROUPS_BY_CITY_REQUEST"
export const FETCH_TOUR_GROUPS_BY_CITY_SUCCESS = "FETCH_TOUR_GROUPS_BY_CITY_SUCCESS"
export const FETCH_TOUR_GROUPS_BY_CITY_FAILURE = "FETCH_TOUR_GROUPS_BY_CITY_FAILURE"

//Fetch variants by tour
export const FETCH_VARIANTS_BY_TOUR_REQUEST = "FETCH_VARIANTS_BY_TOUR_REQUEST"
export const FETCH_VARIANTS_BY_TOUR_SUCCESS = "FETCH_VARIANTS_BY_TOUR_SUCCESS"
export const FETCH_VARIANTS_BY_TOUR_FAILURE = "FETCH_VARIANTS_BY_TOUR_FAILURE"

//Fetch pricing rules by variant
export const FETCH_PRICING_RULES_REQUEST = "FETCH_PRICING_RULES_REQUEST"
export const FETCH_PRICING_RULES_SUCCESS = "FETCH_PRICING_RULES_SUCCESS"
export const FETCH_PRICING_RULES_FAILURE = "FETCH_PRICING_RULES_FAILURE"

//Search tour groups by name
export const SEARCH_TOUR_GROUPS_REQUEST = "SEARCH_TOUR_GROUPS_REQUEST"
export const SEARCH_TOUR_GROUPS_SUCCESS = "SEARCH_TOUR_GROUPS_SUCCESS"
export const SEARCH_TOUR_GROUPS_FAILURE = "SEARCH_TOUR_GROUPS_FAILURE"

//Create pricing rule
export const CREATE_PRICING_RULE_REQUEST = "CREATE_PRICING_RULE_REQUEST"
export const CREATE_PRICING_RULE_SUCCESS = "CREATE_PRICING_RULE_SUCCESS"
export const CREATE_PRICING_RULE_FAILURE = "CREATE_PRICING_RULE_FAILURE"

//Update pricing rule
export const UPDATE_PRICING_RULE_REQUEST = "UPDATE_PRICING_RULE_REQUEST"
export const UPDATE_PRICING_RULE_SUCCESS = "UPDATE_PRICING_RULE_SUCCESS"
export const UPDATE_PRICING_RULE_FAILURE = "UPDATE_PRICING_RULE_FAILURE"

//Delete pricing rule
export const DELETE_PRICING_RULE_REQUEST = "DELETE_PRICING_RULE_REQUEST"
export const DELETE_PRICING_RULE_SUCCESS = "DELETE_PRICING_RULE_SUCCESS"
export const DELETE_PRICING_RULE_FAILURE = "DELETE_PRICING_RULE_FAILURE"

//Fetch date-specific pricing
export const FETCH_DATE_PRICING_REQUEST = "FETCH_DATE_PRICING_REQUEST"
export const FETCH_DATE_PRICING_SUCCESS = "FETCH_DATE_PRICING_SUCCESS"
export const FETCH_DATE_PRICING_FAILURE = "FETCH_DATE_PRICING_FAILURE"

//Create/Update date-specific pricing
export const SAVE_DATE_PRICING_REQUEST = "SAVE_DATE_PRICING_REQUEST"
export const SAVE_DATE_PRICING_SUCCESS = "SAVE_DATE_PRICING_SUCCESS"
export const SAVE_DATE_PRICING_FAILURE = "SAVE_DATE_PRICING_FAILURE"

// Bulk Date Pricing
export const BULK_DATE_PRICING_REQUEST = "BULK_DATE_PRICING_REQUEST"
export const BULK_DATE_PRICING_SUCCESS = "BULK_DATE_PRICING_SUCCESS"
export const BULK_DATE_PRICING_FAILURE = "BULK_DATE_PRICING_FAILURE"

//Fetch variant details
export const FETCH_VARIANT_DETAIL_REQUEST = "FETCH_VARIANT_DETAIL_REQUEST"
export const FETCH_VARIANT_DETAIL_SUCCESS = "FETCH_VARIANT_DETAIL_SUCCESS"
export const FETCH_VARIANT_DETAIL_FAILURE = "FETCH_VARIANT_DETAIL_FAILURE"
//Update variant prices
export const UPDATE_VARIANT_PRICES_REQUEST = "UPDATE_VARIANT_PRICES_REQUEST"
export const UPDATE_VARIANT_PRICES_SUCCESS = "UPDATE_VARIANT_PRICES_SUCCESS"
export const UPDATE_VARIANT_PRICES_FAILURE = "UPDATE_VARIANT_PRICES_FAILURE"

// Klook Mapping
export const FETCH_KLOOK_MAPPINGS_REQUEST = "FETCH_KLOOK_MAPPINGS_REQUEST"
export const FETCH_KLOOK_MAPPINGS_SUCCESS = "FETCH_KLOOK_MAPPINGS_SUCCESS"
export const FETCH_KLOOK_MAPPINGS_FAILURE = "FETCH_KLOOK_MAPPINGS_FAILURE"

export const SEARCH_KLOOK_ACTIVITIES_REQUEST = "SEARCH_KLOOK_ACTIVITIES_REQUEST"
export const SEARCH_KLOOK_ACTIVITIES_SUCCESS = "SEARCH_KLOOK_ACTIVITIES_SUCCESS"
export const SEARCH_KLOOK_ACTIVITIES_FAILURE = "SEARCH_KLOOK_ACTIVITIES_FAILURE"

export const FETCH_KLOOK_ACTIVITY_REQUEST = "FETCH_KLOOK_ACTIVITY_REQUEST"
export const FETCH_KLOOK_ACTIVITY_SUCCESS = "FETCH_KLOOK_ACTIVITY_SUCCESS"
export const FETCH_KLOOK_ACTIVITY_FAILURE = "FETCH_KLOOK_ACTIVITY_FAILURE"

export const BULK_LINK_KLOOK_MAPPINGS_REQUEST = "BULK_LINK_KLOOK_MAPPINGS_REQUEST"
export const BULK_LINK_KLOOK_MAPPINGS_SUCCESS = "BULK_LINK_KLOOK_MAPPINGS_SUCCESS"
export const BULK_LINK_KLOOK_MAPPINGS_FAILURE = "BULK_LINK_KLOOK_MAPPINGS_FAILURE"

// Klook Live Pricing
export const FETCH_KLOOK_LIVE_PRICING_REQUEST = "FETCH_KLOOK_LIVE_PRICING_REQUEST"
export const FETCH_KLOOK_LIVE_PRICING_SUCCESS = "FETCH_KLOOK_LIVE_PRICING_SUCCESS"
export const FETCH_KLOOK_LIVE_PRICING_FAILURE = "FETCH_KLOOK_LIVE_PRICING_FAILURE"

// Create Variant from Klook Package
export const CREATE_VARIANT_FROM_KLOOK_REQUEST = "CREATE_VARIANT_FROM_KLOOK_REQUEST"
export const CREATE_VARIANT_FROM_KLOOK_SUCCESS = "CREATE_VARIANT_FROM_KLOOK_SUCCESS"
export const CREATE_VARIANT_FROM_KLOOK_FAILURE = "CREATE_VARIANT_FROM_KLOOK_FAILURE"
