
export const GET_USER_PERMISSIONS = 'GET_USER_PERMISSIONS';

export const GET_USER_PERMISSIONS_SUCCESS = 'GET_USER_PERMISSIONS_SUCCESS';

export const GET_USER_PERMISSIONS_FAILURE = 'GET_USER_PERMISSIONS_FAILURE';