// Tours
export const GET_TOURS_REQUEST = "GET_TOURS_REQUEST";
export const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS";
export const GET_TOURS_FAIL = "GET_TOURS_FAIL";

// Categories
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

// Sub Categories
export const GET_SUBCATEGORIES_REQUEST = "GET_SUBCATEGORIES_REQUEST";
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS";
export const GET_SUBCATEGORIES_FAIL = "GET_SUBCATEGORIES_FAIL";

// Collections
export const GET_COLLECTIONS_REQUEST = "GET_COLLECTIONS_REQUEST";
export const GET_COLLECTIONS_SUCCESS = "GET_COLLECTIONS_SUCCESS";
export const GET_COLLECTIONS_FAIL = "GET_COLLECTIONS_FAIL";

// Bookings
export const GET_BOOKINGS_REQUEST = "GET_BOOKINGS_REQUEST";
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_FAIL = "GET_BOOKINGS_FAIL";

// Sort Categories
export const SORT_CATEGORY_REQUEST = "SORT_CATEGORY_REQUEST"
export const SORT_CATEGORY_SUCCESS = "SORT_CATEGORY_SUCCESS"
export const SORT_CATEGORY_FAIL = "SORT_CATEGORY_FAIL"

// Sort Categories
export const SORT_SUB_CATEGORY_REQUEST = "SORT_SUB_CATEGORY_REQUEST"
export const SORT_SUB_CATEGORY_SUCCESS = "SORT_SUB_CATEGORY_SUCCESS"
export const SORT_SUB_CATEGORY_FAIL = "SORT_SUB_CATEGORY_FAIL"
