/* EVENTS */
export const GET_CITIES_REQUEST = "GET_CITIES_REQUEST"
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS"
export const GET_CITIES_FAIL = "GET_CITIES_FAIL"

export const GET_CITY_REQUEST = "GET_CITY_REQUEST"
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS"
export const GET_CITY_FAIL = "GET_CITY_FAIL"

export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST"
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS"
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL"  

export const DELETE_CITY_REQUEST = "DELETE_CITY_REQUEST"
export const DELETE_CITY_SUCCESS = "DELETE_CITY_SUCCESS"
export const DELETE_CITY_FAIL = "DELETE_CITY_FAIL"


export const CREATE_NEW_CITY_REQUEST = "CREATE_NEW_CITY_REQUEST"
export const CREATE_NEW_CITY_SUCCESS = "CREATE_NEW_CITY_SUCCESS"
export const CREATE_NEW_CITY_FAIL = "CREATE_NEW_CITY_FAIL"

export const EDIT_CITY_REQUEST = "EDIT_CITY_REQUEST"
export const EDIT_CITY_SUCCESS = "EDIT_CITY_SUCCESS"
export const EDIT_CITY_FAIL = "EDIT_CITY_FAIL"