/* EVENTS */
export const GET_TRAVEL_PARTNERS = "GET_TRAVEL_PARTNERS";
export const GET_TRAVEL_PARTNERS_SUCCESS = "GET_TRAVEL_PARTNERS_SUCCESS";
export const GET_TRAVEL_PARTNERS_FAIL = "GET_TRAVEL_PARTNERS_FAIL";

export const ADD_NEW_TRAVEL_PARTNER = "ADD_NEW_TRAVEL_PARTNER";
export const ADD_TRAVEL_PARTNER_SUCCESS = "ADD_TRAVEL_PARTNER_SUCCESS";
export const ADD_TRAVEL_PARTNER_FAIL = "ADD_TRAVEL_PARTNER_FAIL";

export const UPDATE_TRAVEL_PARTNER = "UPDATE_TRAVEL_PARTNER";
export const UPDATE_TRAVEL_PARTNER_SUCCESS = "UPDATE_TRAVEL_PARTNER_SUCCESS";
export const UPDATE_TRAVEL_PARTNER_FAIL = "UPDATE_TRAVEL_PARTNER_FAIL";

export const DELETE_TRAVEL_PARTNER = "DELETE_TRAVEL_PARTNER";
export const DELETE_TRAVEL_PARTNER_SUCCESS = "DELETE_TRAVEL_PARTNER_SUCCESS";
export const DELETE_TRAVEL_PARTNER_FAIL = "DELETE_TRAVEL_PARTNER_FAIL";
export const RESET_TRAVEL_PARTNER_FLAG = "RESET_TRAVEL_PARTNER_FLAG"
