export const GET_CITIES = "GET_CITIES";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITIES_FAILURE = "GET_CITIES_FAILURE";

export const GET_SECTION_CITIES = "GET_SECTION_CITIES";
export const GET_SECTION_CITIES_SUCCESS = "GET_SECTION_CITIES_SUCCESS";
export const GET_SECTION_CITIES_FAILURE = "GET_SECTION_CITIES_FAILURE";