// Workflow Actions
export const GET_WORKFLOW_LIST = "GET_WORKFLOW_LIST";
export const GET_WORKFLOW_LIST_SUCCESS = "GET_WORKFLOW_LIST_SUCCESS";
export const GET_WORKFLOW_LIST_FAIL = "GET_WORKFLOW_LIST_FAIL";

export const GET_WORKFLOW_BY_ID = "GET_WORKFLOW_BY_ID";
export const GET_WORKFLOW_BY_ID_SUCCESS = "GET_WORKFLOW_BY_ID_SUCCESS";
export const GET_WORKFLOW_BY_ID_FAIL = "GET_WORKFLOW_BY_ID_FAIL";

export const CREATE_WORKFLOW = "CREATE_WORKFLOW";
export const CREATE_WORKFLOW_SUCCESS = "CREATE_WORKFLOW_SUCCESS";
export const CREATE_WORKFLOW_FAIL = "CREATE_WORKFLOW_FAIL";

export const UPDATE_WORKFLOW = "UPDATE_WORKFLOW";
export const UPDATE_WORKFLOW_SUCCESS = "UPDATE_WORKFLOW_SUCCESS";
export const UPDATE_WORKFLOW_FAIL = "UPDATE_WORKFLOW_FAIL";

export const DELETE_WORKFLOW = "DELETE_WORKFLOW";
export const DELETE_WORKFLOW_SUCCESS = "DELETE_WORKFLOW_SUCCESS";
export const DELETE_WORKFLOW_FAIL = "DELETE_WORKFLOW_FAIL";

export const TOGGLE_WORKFLOW_STATUS = "TOGGLE_WORKFLOW_STATUS";
export const TOGGLE_WORKFLOW_STATUS_SUCCESS = "TOGGLE_WORKFLOW_STATUS_SUCCESS";
export const TOGGLE_WORKFLOW_STATUS_FAIL = "TOGGLE_WORKFLOW_STATUS_FAIL";

export const RUN_WORKFLOW = "RUN_WORKFLOW";
export const RUN_WORKFLOW_SUCCESS = "RUN_WORKFLOW_SUCCESS";
export const RUN_WORKFLOW_FAIL = "RUN_WORKFLOW_FAIL";

export const PREVIEW_WORKFLOW_AUDIENCE = "PREVIEW_WORKFLOW_AUDIENCE";
export const PREVIEW_WORKFLOW_AUDIENCE_SUCCESS = "PREVIEW_WORKFLOW_AUDIENCE_SUCCESS";
export const PREVIEW_WORKFLOW_AUDIENCE_FAIL = "PREVIEW_WORKFLOW_AUDIENCE_FAIL";

export const TEST_WORKFLOW_TRIGGER = "TEST_WORKFLOW_TRIGGER";
export const TEST_WORKFLOW_TRIGGER_SUCCESS = "TEST_WORKFLOW_TRIGGER_SUCCESS";
export const TEST_WORKFLOW_TRIGGER_FAIL = "TEST_WORKFLOW_TRIGGER_FAIL";

// Enrollment Actions
export const GET_WORKFLOW_ENROLLMENTS = "GET_WORKFLOW_ENROLLMENTS";
export const GET_WORKFLOW_ENROLLMENTS_SUCCESS = "GET_WORKFLOW_ENROLLMENTS_SUCCESS";
export const GET_WORKFLOW_ENROLLMENTS_FAIL = "GET_WORKFLOW_ENROLLMENTS_FAIL";

export const ENROLL_CUSTOMER = "ENROLL_CUSTOMER";
export const ENROLL_CUSTOMER_SUCCESS = "ENROLL_CUSTOMER_SUCCESS";
export const ENROLL_CUSTOMER_FAIL = "ENROLL_CUSTOMER_FAIL";

export const CANCEL_ENROLLMENT = "CANCEL_ENROLLMENT";
export const CANCEL_ENROLLMENT_SUCCESS = "CANCEL_ENROLLMENT_SUCCESS";
export const CANCEL_ENROLLMENT_FAIL = "CANCEL_ENROLLMENT_FAIL";

export const PROCESS_ENROLLMENT_NOW = "PROCESS_ENROLLMENT_NOW";
export const PROCESS_ENROLLMENT_NOW_SUCCESS = "PROCESS_ENROLLMENT_NOW_SUCCESS";
export const PROCESS_ENROLLMENT_NOW_FAIL = "PROCESS_ENROLLMENT_NOW_FAIL";

// Template Actions
export const GET_EMAIL_TEMPLATES = "GET_EMAIL_TEMPLATES";
export const GET_EMAIL_TEMPLATES_SUCCESS = "GET_EMAIL_TEMPLATES_SUCCESS";
export const GET_EMAIL_TEMPLATES_FAIL = "GET_EMAIL_TEMPLATES_FAIL";

// Segment Actions
export const GET_SEGMENTS = "GET_SEGMENTS";
export const GET_SEGMENTS_SUCCESS = "GET_SEGMENTS_SUCCESS";
export const GET_SEGMENTS_FAIL = "GET_SEGMENTS_FAIL";

export const GET_SEGMENT_BY_ID = "GET_SEGMENT_BY_ID";
export const GET_SEGMENT_BY_ID_SUCCESS = "GET_SEGMENT_BY_ID_SUCCESS";
export const GET_SEGMENT_BY_ID_FAIL = "GET_SEGMENT_BY_ID_FAIL";

export const CREATE_SEGMENT = "CREATE_SEGMENT";
export const CREATE_SEGMENT_SUCCESS = "CREATE_SEGMENT_SUCCESS";
export const CREATE_SEGMENT_FAIL = "CREATE_SEGMENT_FAIL";

export const UPDATE_SEGMENT = "UPDATE_SEGMENT";
export const UPDATE_SEGMENT_SUCCESS = "UPDATE_SEGMENT_SUCCESS";
export const UPDATE_SEGMENT_FAIL = "UPDATE_SEGMENT_FAIL";

export const DELETE_SEGMENT = "DELETE_SEGMENT";
export const DELETE_SEGMENT_SUCCESS = "DELETE_SEGMENT_SUCCESS";
export const DELETE_SEGMENT_FAIL = "DELETE_SEGMENT_FAIL";

export const PREVIEW_SEGMENT = "PREVIEW_SEGMENT";
export const PREVIEW_SEGMENT_SUCCESS = "PREVIEW_SEGMENT_SUCCESS";
export const PREVIEW_SEGMENT_FAIL = "PREVIEW_SEGMENT_FAIL";

export const ADD_SEGMENT_MEMBERS = "ADD_SEGMENT_MEMBERS";
export const ADD_SEGMENT_MEMBERS_SUCCESS = "ADD_SEGMENT_MEMBERS_SUCCESS";
export const ADD_SEGMENT_MEMBERS_FAIL = "ADD_SEGMENT_MEMBERS_FAIL";

export const IMPORT_SEGMENT_FROM_BUCKET = "IMPORT_SEGMENT_FROM_BUCKET";
export const IMPORT_SEGMENT_FROM_BUCKET_SUCCESS = "IMPORT_SEGMENT_FROM_BUCKET_SUCCESS";
export const IMPORT_SEGMENT_FROM_BUCKET_FAIL = "IMPORT_SEGMENT_FROM_BUCKET_FAIL";

// Customer Bucket Actions
export const GET_CUSTOMER_BUCKETS = "GET_CUSTOMER_BUCKETS";
export const GET_CUSTOMER_BUCKETS_SUCCESS = "GET_CUSTOMER_BUCKETS_SUCCESS";
export const GET_CUSTOMER_BUCKETS_FAIL = "GET_CUSTOMER_BUCKETS_FAIL";

export const GET_BUCKET_CUSTOMERS = "GET_BUCKET_CUSTOMERS";
export const GET_BUCKET_CUSTOMERS_SUCCESS = "GET_BUCKET_CUSTOMERS_SUCCESS";
export const GET_BUCKET_CUSTOMERS_FAIL = "GET_BUCKET_CUSTOMERS_FAIL";

// Workflow Audience Actions
export const UPDATE_WORKFLOW_AUDIENCE = "UPDATE_WORKFLOW_AUDIENCE";
export const UPDATE_WORKFLOW_AUDIENCE_SUCCESS = "UPDATE_WORKFLOW_AUDIENCE_SUCCESS";
export const UPDATE_WORKFLOW_AUDIENCE_FAIL = "UPDATE_WORKFLOW_AUDIENCE_FAIL";

export const ADD_WORKFLOW_RECIPIENTS = "ADD_WORKFLOW_RECIPIENTS";
export const ADD_WORKFLOW_RECIPIENTS_SUCCESS = "ADD_WORKFLOW_RECIPIENTS_SUCCESS";
export const ADD_WORKFLOW_RECIPIENTS_FAIL = "ADD_WORKFLOW_RECIPIENTS_FAIL";

export const IMPORT_WORKFLOW_FROM_BUCKET = "IMPORT_WORKFLOW_FROM_BUCKET";
export const IMPORT_WORKFLOW_FROM_BUCKET_SUCCESS = "IMPORT_WORKFLOW_FROM_BUCKET_SUCCESS";
export const IMPORT_WORKFLOW_FROM_BUCKET_FAIL = "IMPORT_WORKFLOW_FROM_BUCKET_FAIL";

// Trigger Types
export const GET_TRIGGER_TYPES = "GET_TRIGGER_TYPES";
export const GET_TRIGGER_TYPES_SUCCESS = "GET_TRIGGER_TYPES_SUCCESS";
export const GET_TRIGGER_TYPES_FAIL = "GET_TRIGGER_TYPES_FAIL";

