// Coupons

export const GET_COUPONS = "GET_COUPONS";
export const ADD_COUPON = "ADD_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";
export const IMPORT_COUPONS = "IMPORT_COUPONS";
export const IMPORT_COUPONS_SUCCESS = "IMPORT_COUPONS_SUCCESS";
export const IMPORT_COUPONS_FAIL = "IMPORT_COUPONS_FAIL";
export const DELETE_COUPON = "DELETE_COUPON";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";