export const GET_FAQS_LIST = "GET_FAQS_LIST"
export const GET_FAQS_LIST_SUCCESS = "GET_FAQS_LIST_SUCCESS"
export const GET_FAQS_LIST_FAIL = "GET_FAQS_LIST_FAIL"

export const ADD_NEW_FAQS = "ADD_NEW_FAQS"
export const ADD_NEW_FAQS_SUCCESS = "ADD_NEW_FAQS_SUCCESS"
export const ADD_NEW_FAQS_FAIL = "ADD_NEW_FAQS_FAIL"

export const UPDATE_FAQS = "UPDATE_FAQS"
export const UPDATE_FAQS_SUCCESS = "UPDATE_FAQS_SUCCESS"
export const UPDATE_FAQS_FAIL = "UPDATE_FAQS_FAIL"
