export const FETCH_PROVIDER_CONFIGS_REQUEST = "FETCH_PROVIDER_CONFIGS_REQUEST";
export const FETCH_PROVIDER_CONFIGS_SUCCESS = "FETCH_PROVIDER_CONFIGS_SUCCESS";
export const FETCH_PROVIDER_CONFIGS_FAILURE = "FETCH_PROVIDER_CONFIGS_FAILURE";

export const CREATE_PROVIDER_CONFIG_REQUEST = "CREATE_PROVIDER_CONFIG_REQUEST";
export const CREATE_PROVIDER_CONFIG_SUCCESS = "CREATE_PROVIDER_CONFIG_SUCCESS";
export const CREATE_PROVIDER_CONFIG_FAILURE = "CREATE_PROVIDER_CONFIG_FAILURE";

export const UPDATE_PROVIDER_CONFIG_REQUEST = "UPDATE_PROVIDER_CONFIG_REQUEST";
export const UPDATE_PROVIDER_CONFIG_SUCCESS = "UPDATE_PROVIDER_CONFIG_SUCCESS";
export const UPDATE_PROVIDER_CONFIG_FAILURE = "UPDATE_PROVIDER_CONFIG_FAILURE";

export const DELETE_PROVIDER_CONFIG_REQUEST = "DELETE_PROVIDER_CONFIG_REQUEST";
export const DELETE_PROVIDER_CONFIG_SUCCESS = "DELETE_PROVIDER_CONFIG_SUCCESS";
export const DELETE_PROVIDER_CONFIG_FAILURE = "DELETE_PROVIDER_CONFIG_FAILURE";

export const FETCH_SUPPORTED_PROVIDERS_REQUEST = "FETCH_SUPPORTED_PROVIDERS_REQUEST";
export const FETCH_SUPPORTED_PROVIDERS_SUCCESS = "FETCH_SUPPORTED_PROVIDERS_SUCCESS";
export const FETCH_SUPPORTED_PROVIDERS_FAILURE = "FETCH_SUPPORTED_PROVIDERS_FAILURE";
