// Globaltix Products
export const FETCH_GLOBALTIX_PRODUCTS_REQUEST = "FETCH_GLOBALTIX_PRODUCTS_REQUEST";
export const FETCH_GLOBALTIX_PRODUCTS_SUCCESS = "FETCH_GLOBALTIX_PRODUCTS_SUCCESS";
export const FETCH_GLOBALTIX_PRODUCTS_FAILURE = "FETCH_GLOBALTIX_PRODUCTS_FAILURE";

export const SEARCH_GLOBALTIX_PRODUCTS_REQUEST = "SEARCH_GLOBALTIX_PRODUCTS_REQUEST";
export const SEARCH_GLOBALTIX_PRODUCTS_SUCCESS = "SEARCH_GLOBALTIX_PRODUCTS_SUCCESS";
export const SEARCH_GLOBALTIX_PRODUCTS_FAILURE = "SEARCH_GLOBALTIX_PRODUCTS_FAILURE";

export const FETCH_GLOBALTIX_PRODUCT_DETAIL_REQUEST = "FETCH_GLOBALTIX_PRODUCT_DETAIL_REQUEST";
export const FETCH_GLOBALTIX_PRODUCT_DETAIL_SUCCESS = "FETCH_GLOBALTIX_PRODUCT_DETAIL_SUCCESS";
export const FETCH_GLOBALTIX_PRODUCT_DETAIL_FAILURE = "FETCH_GLOBALTIX_PRODUCT_DETAIL_FAILURE";

export const LINK_GLOBALTIX_PRODUCT_REQUEST = "LINK_GLOBALTIX_PRODUCT_REQUEST";
export const LINK_GLOBALTIX_PRODUCT_SUCCESS = "LINK_GLOBALTIX_PRODUCT_SUCCESS";
export const LINK_GLOBALTIX_PRODUCT_FAILURE = "LINK_GLOBALTIX_PRODUCT_FAILURE";

// Globaltix Sync
export const GLOBALTIX_SYNC_FULL_REQUEST = "GLOBALTIX_SYNC_FULL_REQUEST";
export const GLOBALTIX_SYNC_FULL_SUCCESS = "GLOBALTIX_SYNC_FULL_SUCCESS";
export const GLOBALTIX_SYNC_FULL_FAILURE = "GLOBALTIX_SYNC_FULL_FAILURE";

export const GLOBALTIX_SYNC_PRODUCT_REQUEST = "GLOBALTIX_SYNC_PRODUCT_REQUEST";
export const GLOBALTIX_SYNC_PRODUCT_SUCCESS = "GLOBALTIX_SYNC_PRODUCT_SUCCESS";
export const GLOBALTIX_SYNC_PRODUCT_FAILURE = "GLOBALTIX_SYNC_PRODUCT_FAILURE";

// Globaltix Bookings
export const FETCH_GLOBALTIX_BOOKINGS_REQUEST = "FETCH_GLOBALTIX_BOOKINGS_REQUEST";
export const FETCH_GLOBALTIX_BOOKINGS_SUCCESS = "FETCH_GLOBALTIX_BOOKINGS_SUCCESS";
export const FETCH_GLOBALTIX_BOOKINGS_FAILURE = "FETCH_GLOBALTIX_BOOKINGS_FAILURE";

export const FETCH_GLOBALTIX_BOOKING_DETAIL_REQUEST = "FETCH_GLOBALTIX_BOOKING_DETAIL_REQUEST";
export const FETCH_GLOBALTIX_BOOKING_DETAIL_SUCCESS = "FETCH_GLOBALTIX_BOOKING_DETAIL_SUCCESS";
export const FETCH_GLOBALTIX_BOOKING_DETAIL_FAILURE = "FETCH_GLOBALTIX_BOOKING_DETAIL_FAILURE";

export const CANCEL_GLOBALTIX_BOOKING_REQUEST = "CANCEL_GLOBALTIX_BOOKING_REQUEST";
export const CANCEL_GLOBALTIX_BOOKING_SUCCESS = "CANCEL_GLOBALTIX_BOOKING_SUCCESS";
export const CANCEL_GLOBALTIX_BOOKING_FAILURE = "CANCEL_GLOBALTIX_BOOKING_FAILURE";

export const CONFIRM_GLOBALTIX_BOOKING_REQUEST = "CONFIRM_GLOBALTIX_BOOKING_REQUEST";
export const CONFIRM_GLOBALTIX_BOOKING_SUCCESS = "CONFIRM_GLOBALTIX_BOOKING_SUCCESS";
export const CONFIRM_GLOBALTIX_BOOKING_FAILURE = "CONFIRM_GLOBALTIX_BOOKING_FAILURE";

export const RELEASE_GLOBALTIX_BOOKING_REQUEST = "RELEASE_GLOBALTIX_BOOKING_REQUEST";
export const RELEASE_GLOBALTIX_BOOKING_SUCCESS = "RELEASE_GLOBALTIX_BOOKING_SUCCESS";
export const RELEASE_GLOBALTIX_BOOKING_FAILURE = "RELEASE_GLOBALTIX_BOOKING_FAILURE";

export const RESEND_GLOBALTIX_EMAIL_REQUEST = "RESEND_GLOBALTIX_EMAIL_REQUEST";
export const RESEND_GLOBALTIX_EMAIL_SUCCESS = "RESEND_GLOBALTIX_EMAIL_SUCCESS";
export const RESEND_GLOBALTIX_EMAIL_FAILURE = "RESEND_GLOBALTIX_EMAIL_FAILURE";

export const REFRESH_GLOBALTIX_BOOKING_REQUEST = "REFRESH_GLOBALTIX_BOOKING_REQUEST";
export const REFRESH_GLOBALTIX_BOOKING_SUCCESS = "REFRESH_GLOBALTIX_BOOKING_SUCCESS";
export const REFRESH_GLOBALTIX_BOOKING_FAILURE = "REFRESH_GLOBALTIX_BOOKING_FAILURE";

// Globaltix Reserve (manual booking creation)
export const RESERVE_GLOBALTIX_BOOKING_REQUEST = "RESERVE_GLOBALTIX_BOOKING_REQUEST";
export const RESERVE_GLOBALTIX_BOOKING_SUCCESS = "RESERVE_GLOBALTIX_BOOKING_SUCCESS";
export const RESERVE_GLOBALTIX_BOOKING_FAILURE = "RESERVE_GLOBALTIX_BOOKING_FAILURE";

// Globaltix Availability
export const FETCH_GLOBALTIX_AVAILABILITY_CALENDAR_REQUEST = "FETCH_GLOBALTIX_AVAILABILITY_CALENDAR_REQUEST";
export const FETCH_GLOBALTIX_AVAILABILITY_CALENDAR_SUCCESS = "FETCH_GLOBALTIX_AVAILABILITY_CALENDAR_SUCCESS";
export const FETCH_GLOBALTIX_AVAILABILITY_CALENDAR_FAILURE = "FETCH_GLOBALTIX_AVAILABILITY_CALENDAR_FAILURE";

export const FETCH_GLOBALTIX_AVAILABILITY_TIMESLOT_REQUEST = "FETCH_GLOBALTIX_AVAILABILITY_TIMESLOT_REQUEST";
export const FETCH_GLOBALTIX_AVAILABILITY_TIMESLOT_SUCCESS = "FETCH_GLOBALTIX_AVAILABILITY_TIMESLOT_SUCCESS";
export const FETCH_GLOBALTIX_AVAILABILITY_TIMESLOT_FAILURE = "FETCH_GLOBALTIX_AVAILABILITY_TIMESLOT_FAILURE";

// Globaltix Auth
export const FETCH_GLOBALTIX_TOKEN_REQUEST = "FETCH_GLOBALTIX_TOKEN_REQUEST";
export const FETCH_GLOBALTIX_TOKEN_SUCCESS = "FETCH_GLOBALTIX_TOKEN_SUCCESS";
export const FETCH_GLOBALTIX_TOKEN_FAILURE = "FETCH_GLOBALTIX_TOKEN_FAILURE";

export const AUTHENTICATE_GLOBALTIX_REQUEST = "AUTHENTICATE_GLOBALTIX_REQUEST";
export const AUTHENTICATE_GLOBALTIX_SUCCESS = "AUTHENTICATE_GLOBALTIX_SUCCESS";
export const AUTHENTICATE_GLOBALTIX_FAILURE = "AUTHENTICATE_GLOBALTIX_FAILURE";

// Globaltix Ticket URLs (download without email)
export const FETCH_GLOBALTIX_TICKET_URLS_REQUEST = "FETCH_GLOBALTIX_TICKET_URLS_REQUEST";
export const FETCH_GLOBALTIX_TICKET_URLS_SUCCESS = "FETCH_GLOBALTIX_TICKET_URLS_SUCCESS";
export const FETCH_GLOBALTIX_TICKET_URLS_FAILURE = "FETCH_GLOBALTIX_TICKET_URLS_FAILURE";

// Globaltix Webhook Events
export const FETCH_GLOBALTIX_WEBHOOK_EVENTS_REQUEST = "FETCH_GLOBALTIX_WEBHOOK_EVENTS_REQUEST";
export const FETCH_GLOBALTIX_WEBHOOK_EVENTS_SUCCESS = "FETCH_GLOBALTIX_WEBHOOK_EVENTS_SUCCESS";
export const FETCH_GLOBALTIX_WEBHOOK_EVENTS_FAILURE = "FETCH_GLOBALTIX_WEBHOOK_EVENTS_FAILURE";

// Razorpay Webhook Events
export const FETCH_RAZORPAY_WEBHOOK_EVENTS_REQUEST = "FETCH_RAZORPAY_WEBHOOK_EVENTS_REQUEST";
export const FETCH_RAZORPAY_WEBHOOK_EVENTS_SUCCESS = "FETCH_RAZORPAY_WEBHOOK_EVENTS_SUCCESS";
export const FETCH_RAZORPAY_WEBHOOK_EVENTS_FAILURE = "FETCH_RAZORPAY_WEBHOOK_EVENTS_FAILURE";

// Globaltix Credit Balance
export const FETCH_GLOBALTIX_CREDIT_REQUEST = "FETCH_GLOBALTIX_CREDIT_REQUEST";
export const FETCH_GLOBALTIX_CREDIT_SUCCESS = "FETCH_GLOBALTIX_CREDIT_SUCCESS";
export const FETCH_GLOBALTIX_CREDIT_FAILURE = "FETCH_GLOBALTIX_CREDIT_FAILURE";

// Globaltix Sweep Expired Reservations
export const TRIGGER_GLOBALTIX_SWEEP_REQUEST = "TRIGGER_GLOBALTIX_SWEEP_REQUEST";
export const TRIGGER_GLOBALTIX_SWEEP_SUCCESS = "TRIGGER_GLOBALTIX_SWEEP_SUCCESS";
export const TRIGGER_GLOBALTIX_SWEEP_FAILURE = "TRIGGER_GLOBALTIX_SWEEP_FAILURE";

// Globaltix Export Bookings CSV
export const EXPORT_GLOBALTIX_BOOKINGS_REQUEST = "EXPORT_GLOBALTIX_BOOKINGS_REQUEST";
export const EXPORT_GLOBALTIX_BOOKINGS_SUCCESS = "EXPORT_GLOBALTIX_BOOKINGS_SUCCESS";
export const EXPORT_GLOBALTIX_BOOKINGS_FAILURE = "EXPORT_GLOBALTIX_BOOKINGS_FAILURE";

// Globaltix Incremental Sync
export const GLOBALTIX_SYNC_INCREMENTAL_REQUEST = "GLOBALTIX_SYNC_INCREMENTAL_REQUEST";
export const GLOBALTIX_SYNC_INCREMENTAL_SUCCESS = "GLOBALTIX_SYNC_INCREMENTAL_SUCCESS";
export const GLOBALTIX_SYNC_INCREMENTAL_FAILURE = "GLOBALTIX_SYNC_INCREMENTAL_FAILURE";

// Globaltix Link/Unlink Booking to TYL Tour Booking
export const LINK_GLOBALTIX_BOOKING_REQUEST = "LINK_GLOBALTIX_BOOKING_REQUEST";
export const LINK_GLOBALTIX_BOOKING_SUCCESS = "LINK_GLOBALTIX_BOOKING_SUCCESS";
export const LINK_GLOBALTIX_BOOKING_FAILURE = "LINK_GLOBALTIX_BOOKING_FAILURE";

export const UNLINK_GLOBALTIX_BOOKING_REQUEST = "UNLINK_GLOBALTIX_BOOKING_REQUEST";
export const UNLINK_GLOBALTIX_BOOKING_SUCCESS = "UNLINK_GLOBALTIX_BOOKING_SUCCESS";
export const UNLINK_GLOBALTIX_BOOKING_FAILURE = "UNLINK_GLOBALTIX_BOOKING_FAILURE";
