// Globaltix Products
export const FETCH_GLOBALTIX_PRODUCTS_REQUEST = "FETCH_GLOBALTIX_PRODUCTS_REQUEST";
export const FETCH_GLOBALTIX_PRODUCTS_SUCCESS = "FETCH_GLOBALTIX_PRODUCTS_SUCCESS";
export const FETCH_GLOBALTIX_PRODUCTS_FAILURE = "FETCH_GLOBALTIX_PRODUCTS_FAILURE";

export const SEARCH_GLOBALTIX_PRODUCTS_REQUEST = "SEARCH_GLOBALTIX_PRODUCTS_REQUEST";
export const SEARCH_GLOBALTIX_PRODUCTS_SUCCESS = "SEARCH_GLOBALTIX_PRODUCTS_SUCCESS";
export const SEARCH_GLOBALTIX_PRODUCTS_FAILURE = "SEARCH_GLOBALTIX_PRODUCTS_FAILURE";

export const FETCH_GLOBALTIX_PRODUCT_DETAIL_REQUEST = "FETCH_GLOBALTIX_PRODUCT_DETAIL_REQUEST";
export const FETCH_GLOBALTIX_PRODUCT_DETAIL_SUCCESS = "FETCH_GLOBALTIX_PRODUCT_DETAIL_SUCCESS";
export const FETCH_GLOBALTIX_PRODUCT_DETAIL_FAILURE = "FETCH_GLOBALTIX_PRODUCT_DETAIL_FAILURE";

export const LINK_GLOBALTIX_PRODUCT_REQUEST = "LINK_GLOBALTIX_PRODUCT_REQUEST";
export const LINK_GLOBALTIX_PRODUCT_SUCCESS = "LINK_GLOBALTIX_PRODUCT_SUCCESS";
export const LINK_GLOBALTIX_PRODUCT_FAILURE = "LINK_GLOBALTIX_PRODUCT_FAILURE";

// Globaltix Sync
export const GLOBALTIX_SYNC_FULL_REQUEST = "GLOBALTIX_SYNC_FULL_REQUEST";
export const GLOBALTIX_SYNC_FULL_SUCCESS = "GLOBALTIX_SYNC_FULL_SUCCESS";
export const GLOBALTIX_SYNC_FULL_FAILURE = "GLOBALTIX_SYNC_FULL_FAILURE";

export const GLOBALTIX_SYNC_PRODUCT_REQUEST = "GLOBALTIX_SYNC_PRODUCT_REQUEST";
export const GLOBALTIX_SYNC_PRODUCT_SUCCESS = "GLOBALTIX_SYNC_PRODUCT_SUCCESS";
export const GLOBALTIX_SYNC_PRODUCT_FAILURE = "GLOBALTIX_SYNC_PRODUCT_FAILURE";

// Globaltix Bookings
export const FETCH_GLOBALTIX_BOOKINGS_REQUEST = "FETCH_GLOBALTIX_BOOKINGS_REQUEST";
export const FETCH_GLOBALTIX_BOOKINGS_SUCCESS = "FETCH_GLOBALTIX_BOOKINGS_SUCCESS";
export const FETCH_GLOBALTIX_BOOKINGS_FAILURE = "FETCH_GLOBALTIX_BOOKINGS_FAILURE";

export const FETCH_GLOBALTIX_BOOKING_DETAIL_REQUEST = "FETCH_GLOBALTIX_BOOKING_DETAIL_REQUEST";
export const FETCH_GLOBALTIX_BOOKING_DETAIL_SUCCESS = "FETCH_GLOBALTIX_BOOKING_DETAIL_SUCCESS";
export const FETCH_GLOBALTIX_BOOKING_DETAIL_FAILURE = "FETCH_GLOBALTIX_BOOKING_DETAIL_FAILURE";

export const CANCEL_GLOBALTIX_BOOKING_REQUEST = "CANCEL_GLOBALTIX_BOOKING_REQUEST";
export const CANCEL_GLOBALTIX_BOOKING_SUCCESS = "CANCEL_GLOBALTIX_BOOKING_SUCCESS";
export const CANCEL_GLOBALTIX_BOOKING_FAILURE = "CANCEL_GLOBALTIX_BOOKING_FAILURE";

// Globaltix Auth
export const FETCH_GLOBALTIX_TOKEN_REQUEST = "FETCH_GLOBALTIX_TOKEN_REQUEST";
export const FETCH_GLOBALTIX_TOKEN_SUCCESS = "FETCH_GLOBALTIX_TOKEN_SUCCESS";
export const FETCH_GLOBALTIX_TOKEN_FAILURE = "FETCH_GLOBALTIX_TOKEN_FAILURE";

export const AUTHENTICATE_GLOBALTIX_REQUEST = "AUTHENTICATE_GLOBALTIX_REQUEST";
export const AUTHENTICATE_GLOBALTIX_SUCCESS = "AUTHENTICATE_GLOBALTIX_SUCCESS";
export const AUTHENTICATE_GLOBALTIX_FAILURE = "AUTHENTICATE_GLOBALTIX_FAILURE";
