export const GET_CAREER_POSTINGS = "GET_CAREER_POSTINGS"
export const GET_CAREER_POSTINGS_SUCCESS = "GET_CAREER_POSTINGS_SUCCESS"
export const GET_CAREER_POSTINGS_FAIL = "GET_CAREER_POSTINGS_FAIL"

export const GET_CAREER_POSTING = "GET_CAREER_POSTING"
export const GET_CAREER_POSTING_SUCCESS = "GET_CAREER_POSTING_SUCCESS"
export const GET_CAREER_POSTING_FAIL = "GET_CAREER_POSTING_FAIL"

export const ADD_NEW_CAREER_POSTING = "ADD_NEW_CAREER_POSTING"
export const ADD_CAREER_POSTING_SUCCESS = "ADD_CAREER_POSTING_SUCCESS"
export const ADD_CAREER_POSTING_FAIL = "ADD_CAREER_POSTING_FAIL"

export const UPDATE_CAREER_POSTING = "UPDATE_CAREER_POSTING"
export const UPDATE_CAREER_POSTING_SUCCESS = "UPDATE_CAREER_POSTING_SUCCESS"
export const UPDATE_CAREER_POSTING_FAIL = "UPDATE_CAREER_POSTING_FAIL"

export const DELETE_CAREER_POSTING = "DELETE_CAREER_POSTING"
export const DELETE_CAREER_POSTING_SUCCESS = "DELETE_CAREER_POSTING_SUCCESS"
export const DELETE_CAREER_POSTING_FAIL = "DELETE_CAREER_POSTING_FAIL"

export const GET_CAREER_APPLICATIONS = "GET_CAREER_APPLICATIONS"
export const GET_CAREER_APPLICATIONS_SUCCESS = "GET_CAREER_APPLICATIONS_SUCCESS"
export const GET_CAREER_APPLICATIONS_FAIL = "GET_CAREER_APPLICATIONS_FAIL"

export const UPDATE_APPLICATION_STATUS = "UPDATE_APPLICATION_STATUS"
export const UPDATE_APPLICATION_STATUS_SUCCESS = "UPDATE_APPLICATION_STATUS_SUCCESS"
export const UPDATE_APPLICATION_STATUS_FAIL = "UPDATE_APPLICATION_STATUS_FAIL"
