export const GET_TRAVEL_CATEGORIES_REQUEST = "GET_TRAVEL_CATEGORIES_REQUEST";
export const GET_TRAVEL_CATEGORIES_SUCCESS = "GET_TRAVEL_CATEGORIES_SUCCESS";
export const GET_TRAVEL_CATEGORIES_FAILURE = "GET_TRAVEL_CATEGORIES_FAILURE";

export const DELETE_TRAVEL_CATEGORY_REQUEST = "DELETE_TRAVEL_CATEGORY_REQUEST";
export const DELETE_TRAVEL_CATEGORY_SUCCESS = "DELETE_TRAVEL_CATEGORY_SUCCESS";
export const DELETE_TRAVEL_CATEGORY_FAILURE = "DELETE_TRAVEL_CATEGORY_FAILURE";

export const FETCH_CITIES_REQUEST = "FETCH_CITIES_REQUEST";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_FAILURE = "FETCH_CITIES_FAILURE";

export const ADD_TRAVEL_CATEGORY_REQUEST = "ADD_TRAVEL_CATEGORY_REQUEST";
export const ADD_TRAVEL_CATEGORY_SUCCESS = "ADD_TRAVEL_CATEGORY_SUCCESS";
export const ADD_TRAVEL_CATEGORY_FAILURE = "ADD_TRAVEL_CATEGORY_FAILURE";

export const RESET_ADD_TRAVEL_CATEGORY = "RESET_ADD_TRAVEL_CATEGORY";

// GET by ID
export const FETCH_TRAVEL_CATEGORY_REQUEST = "FETCH_TRAVEL_CATEGORY_REQUEST";
export const FETCH_TRAVEL_CATEGORY_SUCCESS = "FETCH_TRAVEL_CATEGORY_SUCCESS";
export const FETCH_TRAVEL_CATEGORY_FAILURE = "FETCH_TRAVEL_CATEGORY_FAILURE";

// PUT update
export const UPDATE_TRAVEL_CATEGORY_REQUEST = "UPDATE_TRAVEL_CATEGORY_REQUEST";
export const UPDATE_TRAVEL_CATEGORY_SUCCESS = "UPDATE_TRAVEL_CATEGORY_SUCCESS";
export const UPDATE_TRAVEL_CATEGORY_FAILURE = "UPDATE_TRAVEL_CATEGORY_FAILURE";

// RESET update state
export const RESET_TRAVEL_CATEGORY = "RESET_TRAVEL_CATEGORY";

//View Details
export const VIEW_TRAVEL_CATEGORY_DETAILS_REQUEST = "VIEW_TRAVEL_CATEGORY_DETAILS_REQUEST";
export const VIEW_TRAVEL_CATEGORY_DETAILS_SUCCESS = "VIEW_TRAVEL_CATEGORY_DETAILS_SUCCESS";
export const VIEW_TRAVEL_CATEGORY_DETAILS_FAILURE = "VIEW_TRAVEL_CATEGORY_DETAILS_FAILURE";

//tours
export const FETCH_CATEGORY_TOURS_REQUEST = "FETCH_CATEGORY_TOURS_REQUEST";
export const FETCH_CATEGORY_TOURS_SUCCESS = "FETCH_CATEGORY_TOURS_SUCCESS";
export const FETCH_CATEGORY_TOURS_FAILURE = "FETCH_CATEGORY_TOURS_FAILURE";

//sub categories
export const FETCH_CATEGORY_SUBCATEGORIES_REQUEST = "FETCH_CATEGORY_SUBCATEGORIES_REQUEST";
export const FETCH_CATEGORY_SUBCATEGORIES_SUCCESS = "FETCH_CATEGORY_SUBCATEGORIES_SUCCESS";
export const FETCH_CATEGORY_SUBCATEGORIES_FAILURE = "FETCH_CATEGORY_SUBCATEGORIES_FAILURE";

//bookings
export const FETCH_CATEGORY_BOOKINGS_REQUEST = "FETCH_CATEGORY_BOOKINGS_REQUEST";
export const FETCH_CATEGORY_BOOKINGS_SUCCESS = "FETCH_CATEGORY_BOOKINGS_SUCCESS";
export const FETCH_CATEGORY_BOOKINGS_FAILURE = "FETCH_CATEGORY_BOOKINGS_FAILURE";


