export const GET_DASHBOARD_PERMISSION = "GET_DASHBOARD_PERMISSION"
export const GET_DASHBOARD_PERMISSION_SUCCESS =
  "GET_DASHBOARD_PERMISSION_SUCCESS"
export const GET_DASHBOARD_PERMISSION_FAIL = "GET_DASHBOARD_PERMISSION_FAIL"
