/* EVENTS */
export const ADD_DEFAULT_PRICING = "ADD_DEFAULT_PRICING";
export const ADD_DEFAULT_PRICING_SUCCESS = "ADD_DEFAULT_PRICING_SUCCESS";
export const ADD_DEFAULT_PRICING_FAIL = "ADD_DEFAULT_PRICING_FAIL";

