

export const headerCurrency = [
  { id: "USD", name: "USD", symbol: "$", displayName: "United States Dollar", href: "##",  active: true },
  { id: "AED", name: "AED", symbol: "د.إ", displayName: "United Arab Emirates Dirham", href: "##",  active: true },
  // { id: "AFN", name: "AFN", symbol: "؋", displayName: "Afghan Afghani", href: "##",  active: true },
  { id: "ALL", name: "ALL", symbol: "L", displayName: "Albanian Lek", href: "##",  active: true },
  { id: "AMD", name: "AMD", symbol: "֏", displayName: "Armenian Dram", href: "##",  active: true },
  // { id: "ANG", name: "ANG", symbol: "ƒ", displayName: "Netherlands Antillean Guilder", href: "##",  active: true },
  // { id: "AOA", name: "AOA", symbol: "Kz", displayName: "Angolan Kwanza", href: "##",  active: true },
  { id: "ARS", name: "ARS", symbol: "$", displayName: "Argentine Peso", href: "##",  active: true },
  { id: "AUD", name: "AUD", symbol: "AU$", displayName: "Australian Dollar", href: "##",  active: true },
  { id: "AWG", name: "AWG", symbol: "ƒ", displayName: "Aruban Florin", href: "##",  active: true },
  { id: "AZN", name: "AZN", symbol: "₼", displayName: "Azerbaijani Manat", href: "##",  active: true },
  // { id: "BAM", name: "BAM", symbol: "KM", displayName: "Bosnia Convertible Mark", href: "##",  active: true },
  { id: "BBD", name: "BBD", symbol: "Bds$", displayName: "Barbadian Dollar", href: "##",  active: true },
  { id: "BDT", name: "BDT", symbol: "৳", displayName: "Bangladeshi Taka", href: "##",  active: true },
  { id: "BGN", name: "BGN", symbol: "лв", displayName: "Bulgarian Lev", href: "##",  active: true },
  // { id: "BHD", name: "BHD", symbol: ".د.ب", displayName: "Bahraini Dinar", href: "##",  active: true },
  // { id: "BIF", name: "BIF", symbol: "FBu", displayName: "Burundian Franc", href: "##",  active: true },
  { id: "BMD", name: "BMD", symbol: "$", displayName: "Bermudian Dollar", href: "##",  active: true },
  { id: "BND", name: "BND", symbol: "B$", displayName: "Brunei Dollar", href: "##",  active: true },
  { id: "BOB", name: "BOB", symbol: "Bs.", displayName: "Bolivian Boliviano", href: "##",  active: true },
  { id: "BRL", name: "BRL", symbol: "R$", displayName: "Brazilian Real", href: "##",  active: true },
  { id: "BSD", name: "BSD", symbol: "B$", displayName: "Bahamian Dollar", href: "##",  active: true },
  { id: "BTN", name: "BTN", symbol: "Nu.", displayName: "Bhutanese Ngultrum", href: "##",  active: true },
  { id: "BWP", name: "BWP", symbol: "P", displayName: "Botswana Pula", href: "##",  active: true },
  // { id: "BYN", name: "BYN", symbol: "Br", displayName: "Belarusian Ruble", href: "##",  active: true },
  { id: "BZD", name: "BZD", symbol: "BZ$", displayName: "Belize Dollar", href: "##",  active: true },
  { id: "CAD", name: "CAD", symbol: "CA$", displayName: "Canadian Dollar", href: "##",  active: true },
  // { id: "CDF", name: "CDF", symbol: "FC", displayName: "Congolese Franc", href: "##",  active: true },
  { id: "CHF", name: "CHF", symbol: "CHF", displayName: "Swiss Franc", href: "##",  active: true },
  { id: "CLP", name: "CLP", symbol: "CLP$", displayName: "Chilean Peso", href: "##",  active: true },
  { id: "CNY", name: "CNY", symbol: "¥", displayName: "Chinese Yuan", href: "##",  active: true },
  { id: "COP", name: "COP", symbol: "COL$", displayName: "Colombian Peso", href: "##",  active: true },
  { id: "CRC", name: "CRC", symbol: "₡", displayName: "Costa Rican Colón", href: "##",  active: true },
  { id: "CUP", name: "CUP", symbol: "₱", displayName: "Cuban Peso", href: "##",  active: true },
  { id: "CVE", name: "CVE", symbol: "$", displayName: "Cape Verdean Escudo", href: "##",  active: true },
  { id: "CZK", name: "CZK", symbol: "Kč", displayName: "Czech Koruna", href: "##",  active: true },
  { id: "DJF", name: "DJF", symbol: "Fdj", displayName: "Djiboutian Franc", href: "##",  active: true },
  { id: "DKK", name: "DKK", symbol: "kr", displayName: "Danish Krone", href: "##",  active: true },
  { id: "DOP", name: "DOP", symbol: "RD$", displayName: "Dominican Peso", href: "##",  active: true },
  { id: "DZD", name: "DZD", symbol: "د.ج", displayName: "Algerian Dinar", href: "##",  active: true },
  { id: "EGP", name: "EGP", symbol: "£", displayName: "Egyptian Pound", href: "##",  active: true },
  // { id: "ERN", name: "ERN", symbol: "Nfk", displayName: "Eritrean Nakfa", href: "##",  active: true },
  { id: "ETB", name: "ETB", symbol: "Br", displayName: "Ethiopian Birr", href: "##",  active: true },
  { id: "EUR", name: "EUR", symbol: "€", displayName: "Euro", href: "##",  active: true },
  { id: "FJD", name: "FJD", symbol: "FJ$", displayName: "Fijian Dollar", href: "##",  active: true },
  // { id: "FKP", name: "FKP", symbol: "£", displayName: "Falkland Islands Pound", href: "##",  active: true },
  // { id: "FOK", name: "FOK", symbol: "kr", displayName: "Faroese Króna", href: "##",  active: true },
  { id: "GBP", name: "GBP", symbol: "£", displayName: "British Pound", href: "##",  active: true },
  // { id: "GEL", name: "GEL", symbol: "₾", displayName: "Georgian Lari", href: "##",  active: true },
  // { id: "GGP", name: "GGP", symbol: "£", displayName: "Guernsey Pound", href: "##",  active: true },
  { id: "GHS", name: "GHS", symbol: "₵", displayName: "Ghanaian Cedi", href: "##",  active: true },
  { id: "GIP", name: "GIP", symbol: "£", displayName: "Gibraltar Pound", href: "##",  active: true },
  { id: "GMD", name: "GMD", symbol: "D", displayName: "Gambian Dalasi", href: "##",  active: true },
  { id: "GNF", name: "GNF", symbol: "FG", displayName: "Guinean Franc", href: "##",  active: true },
  { id: "GTQ", name: "GTQ", symbol: "Q", displayName: "Guatemalan Quetzal", href: "##",  active: true },
  { id: "GYD", name: "GYD", symbol: "G$", displayName: "Guyanese Dollar", href: "##",  active: true },
  { id: "HKD", name: "HKD", symbol: "HK$", displayName: "Hong Kong Dollar", href: "##",  active: true },
  { id: "HNL", name: "HNL", symbol: "L", displayName: "Honduran Lempira", href: "##",  active: true },
  { id: "HRK", name: "HRK", symbol: "kn", displayName: "Croatian Kuna", href: "##",  active: true },
  { id: "HTG", name: "HTG", symbol: "G", displayName: "Haitian Gourde", href: "##",  active: true },
  { id: "HUF", name: "HUF", symbol: "Ft", displayName: "Hungarian Forint", href: "##",  active: true },
  { id: "IDR", name: "IDR", symbol: "Rp", displayName: "Indonesian Rupiah", href: "##",  active: true },
  { id: "ILS", name: "ILS", symbol: "₪", displayName: "Israeli New Shekel", href: "##",  active: true },
  // { id: "IMP", name: "IMP", symbol: "£", displayName: "Isle of Man Pound", href: "##",  active: true },
  { id: "INR", name: "INR", symbol: "₹", displayName: "Indian Rupee", href: "##",  active: true },
  { id: "IQD", name: "IQD", symbol: "ع.د", displayName: "Iraqi Dinar", href: "##",  active: true },
  // { id: "IRR", name: "IRR", symbol: "﷼", displayName: "Iranian Rial", href: "##",  active: true },
  { id: "ISK", name: "ISK", symbol: "kr", displayName: "Icelandic Króna", href: "##",  active: true },
  { id: "JEP", name: "JEP", symbol: "£", displayName: "Jersey Pound", href: "##",  active: true },
  { id: "JMD", name: "JMD", symbol: "J$", displayName: "Jamaican Dollar", href: "##",  active: true },
  { id: "JOD", name: "JOD", symbol: "د.ا", displayName: "Jordanian Dinar", href: "##",  active: true },
  // { id: "JPY", name: "JPY", symbol: "¥", displayName: "Japanese Yen", href: "##",  active: true },
  { id: "KES", name: "KES", symbol: "KSh", displayName: "Kenyan Shilling", href: "##",  active: true },
  { id: "KGS", name: "KGS", symbol: "сом", displayName: "Kyrgyzstani Som", href: "##",  active: true },
  { id: "KHR", name: "KHR", symbol: "៛", displayName: "Cambodian Riel", href: "##",  active: true },
  // { id: "KID", name: "KID", symbol: "$", displayName: "Kiribati Dollar", href: "##",  active: true },
  { id: "KMF", name: "KMF", symbol: "CF", displayName: "Comorian Franc", href: "##",  active: true },
  { id: "KRW", name: "KRW", symbol: "₩", displayName: "South Korean Won", href: "##",  active: true },
  // { id: "KWD", name: "KWD", symbol: "د.ك", displayName: "Kuwaiti Dinar", href: "##",  active: true },
  { id: "KYD", name: "KYD", symbol: "$", displayName: "Cayman Islands Dollar", href: "##",  active: true },
  { id: "KZT", name: "KZT", symbol: "₸", displayName: "Kazakhstani Tenge", href: "##",  active: true },
  { id: "LAK", name: "LAK", symbol: "₭", displayName: "Lao Kip", href: "##",  active: true },
  // { id: "LBP", name: "LBP", symbol: "ل.ل", displayName: "Lebanese Pound", href: "##",  active: true },
  { id: "LKR", name: "LKR", symbol: "Rs", displayName: "Sri Lankan Rupee", href: "##",  active: true },
  { id: "LRD", name: "LRD", symbol: "$", displayName: "Liberian Dollar", href: "##",  active: true },
  { id: "LSL", name: "LSL", symbol: "L", displayName: "Lesotho Loti", href: "##",  active: true },
  // { id: "LYD", name: "LYD", symbol: "ل.د", displayName: "Libyan Dinar", href: "##",  active: true },
  { id: "MAD", name: "MAD", symbol: "د.م.", displayName: "Moroccan Dirham", href: "##",  active: true },
  { id: "MDL", name: "MDL", symbol: "L", displayName: "Moldovan Leu", href: "##",  active: true },
  { id: "MGA", name: "MGA", symbol: "Ar", displayName: "Malagasy Ariary", href: "##",  active: true },
  { id: "MKD", name: "MKD", symbol: "ден", displayName: "Macedonian Denar", href: "##",  active: true },
  { id: "MMK", name: "MMK", symbol: "K", displayName: "Myanmar Kyat", href: "##",  active: true },
  { id: "MNT", name: "MNT", symbol: "₮", displayName: "Mongolian Tögrög", href: "##",  active: true },
  { id: "MOP", name: "MOP", symbol: "MOP$", displayName: "Macanese Pataca", href: "##",  active: true },
  // { id: "MRU", name: "MRU", symbol: "UM", displayName: "Mauritanian Ouguiya", href: "##",  active: true },
  { id: "MUR", name: "MUR", symbol: "₨", displayName: "Mauritian Rupee", href: "##",  active: true },
  { id: "MVR", name: "MVR", symbol: "Rf", displayName: "Maldivian Rufiyaa", href: "##",  active: true },
  { id: "MWK", name: "MWK", symbol: "MK", displayName: "Malawian Kwacha", href: "##",  active: true },
  { id: "MXN", name: "MXN", symbol: "$", displayName: "Mexican Peso", href: "##",  active: true },
  { id: "MYR", name: "MYR", symbol: "RM", displayName: "Malaysian Ringgit", href: "##",  active: true },
  { id: "MZN", name: "MZN", symbol: "MT", displayName: "Mozambican Metical", href: "##",  active: true },
  { id: "NAD", name: "NAD", symbol: "$", displayName: "Namibian Dollar", href: "##",  active: true },
  { id: "NGN", name: "NGN", symbol: "₦", displayName: "Nigerian Naira", href: "##",  active: true },
  { id: "NIO", name: "NIO", symbol: "C$", displayName: "Nicaraguan Córdoba", href: "##",  active: true },
  { id: "NOK", name: "NOK", symbol: "kr", displayName: "Norwegian Krone", href: "##",  active: true },
  { id: "NPR", name: "NPR", symbol: "Rs", displayName: "Nepalese Rupee", href: "##",  active: true },
  { id: "NZD", name: "NZD", symbol: "NZ$", displayName: "New Zealand Dollar", href: "##",  active: true },
  // { id: "OMR", name: "OMR", symbol: "ر.ع.", displayName: "Omani Rial", href: "##",  active: true },
  // { id: "PAB", name: "PAB", symbol: "B/.", displayName: "Panamanian Balboa", href: "##",  active: true },
  { id: "PEN", name: "PEN", symbol: "S/", displayName: "Peruvian Sol", href: "##",  active: true },
  { id: "PGK", name: "PGK", symbol: "K", displayName: "Papua New Guinean Kina", href: "##",  active: true },
  { id: "PHP", name: "PHP", symbol: "₱", displayName: "Philippine Peso", href: "##",  active: true },
  { id: "PKR", name: "PKR", symbol: "₨", displayName: "Pakistani Rupee", href: "##",  active: true },
  { id: "PLN", name: "PLN", symbol: "zł", displayName: "Polish Złoty", href: "##",  active: true },
  { id: "PYG", name: "PYG", symbol: "₲", displayName: "Paraguayan Guaraní", href: "##",  active: true },
  { id: "QAR", name: "QAR", symbol: "ر.ق", displayName: "Qatari Riyal", href: "##",  active: true },
  { id: "RON", name: "RON", symbol: "lei", displayName: "Romanian Leu", href: "##",  active: true },
  { id: "RSD", name: "RSD", symbol: "дин.", displayName: "Serbian Dinar", href: "##",  active: true },
  { id: "RUB", name: "RUB", symbol: "₽", displayName: "Russian Ruble", href: "##",  active: true },
  { id: "RWF", name: "RWF", symbol: "FRw", displayName: "Rwandan Franc", href: "##",  active: true },
  { id: "SAR", name: "SAR", symbol: "ر.س", displayName: "Saudi Riyal", href: "##",  active: true },
  // { id: "SBD", name: "SBD", symbol: "$", displayName: "Solomon Islands Dollar", href: "##",  active: true },
  { id: "SCR", name: "SCR", symbol: "₨", displayName: "Seychellois Rupee", href: "##",  active: true },
  // { id: "SDG", name: "SDG", symbol: "£", displayName: "Sudanese Pound", href: "##",  active: true },
  { id: "SEK", name: "SEK", symbol: "kr", displayName: "Swedish Krona", href: "##",  active: true },
  { id: "SGD", name: "SGD", symbol: "S$", displayName: "Singapore Dollar", href: "##",  active: true },
  // { id: "SHP", name: "SHP", symbol: "£", displayName: "Saint Helena Pound", href: "##",  active: true },
  // { id: "SLE", name: "SLE", symbol: "Le", displayName: "Sierra Leonean Leone", href: "##",  active: true },
  { id: "SLL", name: "SLL", symbol: "Le", displayName: "Sierra Leonean Leone (Old)", href: "##",  active: true },
  { id: "SOS", name: "SOS", symbol: "Sh", displayName: "Somali Shilling", href: "##",  active: true },
  // { id: "SRD", name: "SRD", symbol: "$", displayName: "Surinamese Dollar", href: "##",  active: true },
  { id: "SSP", name: "SSP", symbol: "£", displayName: "South Sudanese Pound", href: "##",  active: true },
  // { id: "STN", name: "STN", symbol: "Db", displayName: "São Tomé and Príncipe Dobra", href: "##",  active: true },
  // { id: "SYP", name: "SYP", symbol: "£", displayName: "Syrian Pound", href: "##",  active: true },
  { id: "SZL", name: "SZL", symbol: "L", displayName: "Swazi Lilangeni", href: "##",  active: true },
  { id: "THB", name: "THB", symbol: "฿", displayName: "Thai Baht", href: "##",  active: true },
  // { id: "TJS", name: "TJS", symbol: "ЅМ", displayName: "Tajikistani Somoni", href: "##",  active: true },
  // { id: "TMT", name: "TMT", symbol: "m", displayName: "Turkmenistani Manat", href: "##",  active: true },
  { id: "TND", name: "TND", symbol: "د.ت", displayName: "Tunisian Dinar", href: "##",  active: true },
  // { id: "TOP", name: "TOP", symbol: "T$", displayName: "Tongan Paʻanga", href: "##",  active: true },
  { id: "TRY", name: "TRY", symbol: "₺", displayName: "Turkish Lira", href: "##",  active: true },
  { id: "TTD", name: "TTD", symbol: "TT$", displayName: "Trinidad and Tobago Dollar", href: "##",  active: true },
  // { id: "TVD", name: "TVD", symbol: "$", displayName: "Tuvaluan Dollar", href: "##",  active: true },
  { id: "TWD", name: "TWD", symbol: "NT$", displayName: "New Taiwan Dollar", href: "##",  active: true },
  { id: "TZS", name: "TZS", symbol: "TSh", displayName: "Tanzanian Shilling", href: "##",  active: true },
  { id: "UAH", name: "UAH", symbol: "₴", displayName: "Ukrainian Hryvnia", href: "##",  active: true },
  { id: "UGX", name: "UGX", symbol: "USh", displayName: "Ugandan Shilling", href: "##",  active: true },
  // { id: "UYU", name: "UYU", symbol: "$U", displayName: "Uruguayan Peso", href: "##",  active: true },
  { id: "UZS", name: "UZS", symbol: "soʻm", displayName: "Uzbekistani Soʻm", href: "##",  active: true },
  // { id: "VES", name: "VES", symbol: "Bs.", displayName: "Venezuelan Bolívar", href: "##",  active: true },
  { id: "VND", name: "VND", symbol: "₫", displayName: "Vietnamese Đồng", href: "##",  active: true },
  { id: "VUV", name: "VUV", symbol: "VT", displayName: "Vanuatu Vatu", href: "##",  active: true },
  // { id: "WST", name: "WST", symbol: "T", displayName: "Samoan Tālā", href: "##",  active: true },
  { id: "XAF", name: "XAF", symbol: "FCFA", displayName: "Central African CFA Franc", href: "##",  active: true },
  { id: "XCD", name: "XCD", symbol: "EC$", displayName: "East Caribbean Dollar", href: "##",  active: true },
  // { id: "XCG", name: "XCG", symbol: "⛁", displayName: "Cryptocurrency Gold", href: "##",  active: true },
  // { id: "XDR", name: "XDR", symbol: "SDR", displayName: "IMF Special Drawing Rights", href: "##",  active: true },
  { id: "XOF", name: "XOF", symbol: "CFA", displayName: "West African CFA Franc", href: "##",  active: true },
  { id: "XPF", name: "XPF", symbol: "₣", displayName: "CFP Franc (French Pacific)", href: "##",  active: true },
  { id: "YER", name: "YER", symbol: "﷼", displayName: "Yemeni Rial", href: "##",  active: true },
  { id: "ZAR", name: "ZAR", symbol: "R", displayName: "South African Rand", href: "##",  active: true },
  { id: "ZMW", name: "ZMW", symbol: "ZK", displayName: "Zambian Kwacha", href: "##",  active: true },
  // { id: "ZWL", name: "ZWL", symbol: "Z$", displayName: "Zimbabwean Dollar", href: "##",  active: true }
];