// Get List of Tour Group Variants
export const GET_TOUR_GROUP_VARIANTS = "GET_TOUR_GROUP_VARIANTS";
export const GET_TOUR_GROUP_VARIANTS_SUCCESS =
  "GET_TOUR_GROUP_VARIANTS_SUCCESS";
export const GET_TOUR_GROUP_VARIANTS_ERROR = "GET_TOUR_GROUP_VARIANTS_ERROR";

// Get Tour_Group List For Dropdown
export const GET_TRAVEL_TOUR_GROUPS = "GET_TRAVEL_TOUR_GROUPS";
export const GET_TRAVEL_TOUR_GROUPS_SUCCESS = "GET_TRAVEL_TOUR_GROUPS_SUCCESS";
export const GET_TRAVEL_TOUR_GROUPS_FAIL = "GET_TRAVEL_TOUR_GROUPS_FAIL";

// Add Tour Group Variant
export const ADD_TOUR_GROUP_VARIANT = "ADD_TOUR_GROUP_VARIANT";
export const ADD_TOUR_GROUP_VARIANT_SUCCESS = "ADD_TOUR_GROUP_VARIANT_SUCCESS";
export const ADD_TOUR_GROUP_VARIANT_FAIL = "ADD_TOUR_GROUP_VARIANT_FAIL";

// Update Tour Group Varinat
export const UPDATE_TOUR_GROUP_VARIANT = "UPDATE_TOUR_GROUP_VARIANT";
export const UPDATE_TOUR_GROUP_VARIANT_SUCCESS =
  "UPDATE_TOUR_GROUP_VARIANT_SUCCESS";
export const UPDATE_TOUR_GROUP_VARIANT_FAIL = "UPDATE_TOUR_GROUP_VARIANT_FAIL";

// GET TOUR GROUP DETAIL
export const GET_TOUR_GROUP_VARIANT_DETAIL = "GET_TOUR_GROUP_VARIANT_DETAIL";
export const GET_TOUR_GROUP_VARIANT_DETAIL_SUCCESS =
  "GET_TOUR_GROUP_VARIANT_DETAIL_SUCCESS";
export const GET_TOUR_GROUP_VARIANT_DETAIL_FAIL =
  "GET_TOUR_GROUP_VARIANT_DETAIL_FAIL";

// GET PRICING LIST
export const GET_PRICING_LIST = "GET_PRICING_LIST";
export const GET_PRICING_LIST_SUCCESS = "GET_PRICING_LIST_SUCCESS";
export const GET_PRICING_LIST_FAIL = "GET_PRICING_LIST_FAIL";

// GET BOOKING LIST
export const GET_BOOKING_LIST = "GET_BOOKING_LIST";
export const GET_BOOKING_LIST_SUCCESS = "GET_BOOKING_LIST_SUCCESS";
export const GET_BOOKING_LIST_FAIL = "GET_BOOKING_LIST_FAIL";

// // Get List of Tour Group Variants For Dropdown
export const GET_TOUR_GROUP_VARIANT_BY_ID = "GET_TOUR_GROUP_VARIANT_BY_ID";
export const GET_TOUR_GROUP_VARIANT_BY_ID_SUCCESS =
  "GET_TOUR_GROUP_VARIANT_BY_ID_SUCCESS";
export const GET_TOUR_GROUP_VARIANT_BY_ID_FAIL =
  "GET_TOUR_GROUP_VARIANT_BY_ID_FAIL";

// Delete Tour Group Variant
export const DELETE_TOUR_GROUP_VARIANT = "DELETE_TOUR_GROUP_VARIANT";
export const DELETE_TOUR_GROUP_VARIANT_SUCCESS =
  "DELETE_TOUR_GROUP_VARIANT_SUCCESS";
export const DELETE_TOUR_GROUP_VARIANT_FAIL =
  "DELETE_TOUR_GROUP_VARIANT_FAIL";
