// Get List of Tour Group Variants
export const GET_TOUR_GROUP_VARIANTS = "GET_TOUR_GROUP_VARIANTS";
export const GET_TOUR_GROUP_VARIANTS_SUCCESS =
  "GET_TOUR_GROUP_VARIANTS_SUCCESS";
export const GET_TOUR_GROUP_VARIANTS_ERROR = "GET_TOUR_GROUP_VARIANTS_ERROR";

// Get Tour_Group List For Dropdown
export const GET_TRAVEL_TOUR_GROUPS = "GET_TRAVEL_TOUR_GROUPS";
export const GET_TRAVEL_TOUR_GROUPS_SUCCESS = "GET_TRAVEL_TOUR_GROUPS_SUCCESS";
export const GET_TRAVEL_TOUR_GROUPS_FAIL = "GET_TRAVEL_TOUR_GROUPS_FAIL";

// Add Tour Group Variant
export const ADD_TOUR_GROUP_VARIANT = "ADD_TOUR_GROUP_VARIANT";
export const ADD_TOUR_GROUP_VARIANT_SUCCESS = "ADD_TOUR_GROUP_VARIANT_SUCCESS";
export const ADD_TOUR_GROUP_VARIANT_FAIL = "ADD_TOUR_GROUP_VARIANT_FAIL";

// Update Tour Group Varinat
export const UPDATE_TOUR_GROUP_VARIANT = "UPDATE_TOUR_GROUP_VARIANT";
export const UPDATE_TOUR_GROUP_VARIANT_SUCCESS =
  "UPDATE_TOUR_GROUP_VARIANT_SUCCESS";
export const UPDATE_TOUR_GROUP_VARIANT_FAIL = "UPDATE_TOUR_GROUP_VARIANT_FAIL";
