/* EVENTS */
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS";
export const GET_SUBCATEGORIES_FAIL = "GET_SUBCATEGORIES_FAIL";
export const CLEAR_SELECTED_SUBCATEGORY = "CLEAR_SELECTED_SUBCATEGORY";

export const GET_TRAVEL_CATEGORIES="GET_TRAVEL_CATEGORIES"
export const GET_TRAVEL_CATEGORIES_SUCCESS="GET_TRAVEL_CATEGORIES_SUCCESS"
export const GET_TRAVEL_CATEGORIES_FAIL="GET_TRAVEL_CATEGORIES_FAIL"

export const GET_EXISTING_SUBCATEGORY = "GET_EXISTING_SUBCATEGORY";
export const GET_EXISTING_SUBCATEGORY_SUCCESS = "GET_EXISTING_SUBCATEGORY_SUCCESS";
export const GET_EXISTING_SUBCATEGORY_FAIL = "GET_EXISTING_SUBCATEGORY_FAIL";


export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORIES";
export const UPDATE_SUBCATEGORY_SUCCESS = "UPDATE_SUBCATEGORIES_SUCCESS";
export const UPDATE_SUBCATEGORY_FAIL = "UPDATE_SUBCATEGORIES_FAIL";
export const RESET_UPDATE_SUBCATEGORY_STATUS="RESET_UPDATE_SUBCATEGORY_STATUS"

export const ADD_TRAVEL_SUBCATEGORY = "ADD_TRAVEL_SUBCATEGORY";
export const ADD_TRAVEL_SUBCATEGORY_SUCCESS = "ADD_TRAVEL_SUBCATEGORY_SUCCESS";
export const ADD_TRAVEL_SUBCATEGORY_FAIL = "ADD_TRAVEL_SUBCATEGORY_FAIL";
export const RESET_ADD_SUBCATEGORY_STATUS = 'RESET_ADD_SUBCATEGORY_STATUS'; 

export const RESET_SUBCATEGORY_STATUS = "RESET_SUBCATEGORY_STATUS"; // Reset status for both add and update subcategory actions
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAIL = "DELETE_SUBCATEGORY_FAIL";
